#!/bin/bash
# First, remove the old products block completely.
# Then insert the new products block.

# We will use awk to replace the section starting at "// --- PRODUCTS ---" up to right before "// --- SUPPLIERS ---"

awk '
BEGIN { skip = 0; }
/^\s*\/\/ --- PRODUCTS ---/ {
    skip = 1;
    print "// --- PRODUCTS ---"
    print "  app.get(\"/api/products\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const { search, lowStock, inStock, warehouseId } = req.query;"
    print "      let conditions = [];"
    print "      conditions.push(eq(products.isHidden, false));"
    print "      if (warehouseId) conditions.push(eq(products.warehouseId, Number(warehouseId)));"
    print "      if (search) {"
    print "        const searchPattern = `\\%${search}\\%`;"
    print "        conditions.push(or("
    print "          like(products.name, searchPattern),"
    print "          like(products.code, searchPattern),"
    print "          like(products.category, searchPattern)"
    print "        ));"
    print "      }"
    print "      if (lowStock === \"true\") conditions.push(sql`${products.quantity} <= ${products.minStock}`);"
    print "      if (inStock === \"true\") conditions.push(sql`${products.quantity} > 0`);"
    print "      const query = db.select().from(products);"
    print "      if (conditions.length > 0) query.where(and(...conditions));"
    print "      const result = await query.orderBy(desc(products.id));"
    print "      res.json(result);"
    print "    } catch (error: any) {"
    print "      console.error(\"GET /api/products failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to load products\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.post(\"/api/products\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const { code, name, category, unit, quantity, price, minStock, warehouseId } = req.body;"
    print "      if (!code || !name || !warehouseId) return res.status(400).json({ error: \"Code, Name and Warehouse are required\" });"
    print "      const [existing] = await db.select().from(products).where(eq(products.code, code));"
    print "      if (existing) return res.status(400).json({ error: \"Product code already exists\" });"
    print "      const [newProd] = await db.insert(products)"
    print "        .values({"
    print "          code,"
    print "          name,"
    print "          category: category || \"Chưa phân loại\","
    print "          unit: unit || \"\","
    print "          quantity: Number(quantity) || 0,"
    print "          price: Number(price) || 0,"
    print "          minStock: Number(minStock) || 10,"
    print "          warehouseId: Number(warehouseId)"
    print "        })"
    print "        .returning();"
    print "      if (newProd.quantity > 0) {"
    print "        await db.insert(stockTransactions).values({"
    print "          productId: newProd.id,"
    print "          type: \"NHAP\","
    print "          quantity: newProd.quantity,"
    print "          note: \"Nhập tồn kho khởi tạo khi thêm mới sản phẩm\","
    print "          userEmail: req.user?.email || \"system\","
    print "          warehouseId: Number(warehouseId)"
    print "        });"
    print "      }"
    print "      res.status(201).json(newProd);"
    print "    } catch (error: any) {"
    print "      console.error(\"POST /api/products failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to create product\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.put(\"/api/products/:id\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const id = parseInt(req.params.id);"
    print "      const { code, name, category, unit, price, quantity, minStock } = req.body;"
    print "      if (!code || !name) return res.status(400).json({ error: \"Code and Name are required\" });"
    print "      const updateData: any = {"
    print "        code, name, category,"
    print "        unit: unit || \"\","
    print "        price: Number(price) || 0,"
    print "        minStock: Number(minStock) || 0,"
    print "        updatedAt: new Date(),"
    print "      };"
    print "      if (quantity !== undefined) updateData.quantity = Number(quantity);"
    print "      const [updated] = await db.update(products).set(updateData).where(eq(products.id, id)).returning();"
    print "      if (!updated) return res.status(404).json({ error: \"Product not found\" });"
    print "      res.json(updated);"
    print "    } catch (error: any) {"
    print "      console.error(\"PUT /api/products failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to update product\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.patch(\"/api/products/:id/hide\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const id = parseInt(req.params.id);"
    print "      const [updated] = await db.update(products).set({ isHidden: true, updatedAt: new Date() }).where(eq(products.id, id)).returning();"
    print "      if (!updated) return res.status(404).json({ error: \"Product not found\" });"
    print "      res.json({ message: \"Product hidden successfully\" });"
    print "    } catch (error: any) {"
    print "      console.error(\"PATCH /api/products/:id/hide failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to hide product\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.post(\"/api/products/stock-transaction\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const { productId, type, quantity, note, warehouseId } = req.body;"
    print "      const qty = Number(quantity);"
    print "      if (!productId || !type || isNaN(qty) || qty <= 0 || !warehouseId) return res.status(400).json({ error: \"Invalid request\" });"
    print "      const [product] = await db.select().from(products).where(and(eq(products.id, Number(productId)), eq(products.warehouseId, Number(warehouseId))));"
    print "      if (!product) return res.status(404).json({ error: \"Product not found in this warehouse\" });"
    print "      let newQty = product.quantity;"
    print "      if (type === \"NHAP\") {"
    print "        newQty += qty;"
    print "      } else if (type === \"XUAT\") {"
    print "        if (product.quantity < qty) return res.status(400).json({ error: `Not enough stock (current: ${product.quantity})` });"
    print "        newQty -= qty;"
    print "      } else {"
    print "        return res.status(400).json({ error: \"Invalid type\" });"
    print "      }"
    print "      await db.update(products).set({ quantity: newQty, updatedAt: new Date() }).where(eq(products.id, product.id));"
    print "      const [tx] = await db.insert(stockTransactions).values({"
    print "        productId: product.id,"
    print "        type,"
    print "        quantity: qty,"
    print "        note: note || (type === \"NHAP\" ? \"Nhập kho thủ công\" : \"Xuất kho thủ công\"),"
    print "        userEmail: req.user?.email || \"system\","
    print "        warehouseId: Number(warehouseId)"
    print "      }).returning();"
    print "      res.json({ product: { ...product, quantity: newQty }, transaction: tx });"
    print "    } catch (error: any) {"
    print "      console.error(\"POST /api/products/stock-transaction failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to perform stock action\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.get(\"/api/products/:id/transactions\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const id = parseInt(req.params.id);"
    print "      const [product] = await db.select().from(products).where(eq(products.id, id));"
    print "      if (!product) return res.status(404).json({ error: \"Product not found\" });"
    print "      const txList = await db.select().from(stockTransactions).where(eq(stockTransactions.productId, id)).orderBy(asc(stockTransactions.id));"
    print "      let runningBalance = 0;"
    print "      const enrichedList = txList.map(tx => {"
    print "        if (tx.type === \"NHAP\" || tx.type === \"BO_GHI_SO\") {"
    print "          runningBalance += tx.quantity;"
    print "        } else if (tx.type === \"XUAT\" || tx.type === \"GHI_SO\") {"
    print "          runningBalance -= tx.quantity;"
    print "        }"
    print "        return { ...tx, runningBalance };"
    print "      });"
    print "      res.json(enrichedList.reverse());"
    print "    } catch (error: any) {"
    print "      console.error(\"GET transactions failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to load history\" });"
    print "    }"
    print "  });"
    print ""
    print "  app.post(\"/api/products/import\", requireAuth, async (req: AuthRequest, res) => {"
    print "    try {"
    print "      const { items, warehouseId } = req.body;"
    print "      if (!Array.isArray(items) || items.length === 0 || !warehouseId) return res.status(400).json({ error: \"Invalid items or missing warehouseId\" });"
    print "      let importedCount = 0;"
    print "      let skippedCount = 0;"
    print "      for (const item of items) {"
    print "        const { code, name, category, unit, quantity, price, minStock } = item;"
    print "        if (!code || !name) { skippedCount++; continue; }"
    print "        const trimmedCode = String(code).trim();"
    print "        if (!trimmedCode) { skippedCount++; continue; }"
    print "        const [existing] = await db.select().from(products).where(eq(products.code, trimmedCode));"
    print "        if (existing) { skippedCount++; continue; }"
    print "        const qty = Number(quantity) || 0;"
    print "        const prc = Math.round(Number(price)) || 0;"
    print "        const mst = Math.round(Number(minStock)) || 10;"
    print "        const [newProd] = await db.insert(products)"
    print "          .values({"
    print "            code: trimmedCode,"
    print "            name: String(name).trim(),"
    print "            category: category ? String(category).trim() : \"Chưa phân loại\","
    print "            unit: unit ? String(unit).trim() : \"\","
    print "            quantity: qty,"
    print "            price: prc,"
    print "            minStock: mst,"
    print "            warehouseId: Number(warehouseId)"
    print "          })"
    print "          .returning();"
    print "        if (qty > 0) {"
    print "          await db.insert(stockTransactions).values({"
    print "            productId: newProd.id,"
    print "            type: \"NHAP\","
    print "            quantity: qty,"
    print "            note: \"Nhập tồn kho khởi tạo từ import Excel\","
    print "            userEmail: req.user?.email || \"system\","
    print "            warehouseId: Number(warehouseId)"
    print "          });"
    print "        }"
    print "        importedCount++;"
    print "      }"
    print "      res.json({ message: \"Import completed\", importedCount, skippedCount });"
    print "    } catch (error: any) {"
    print "      console.error(\"POST /api/products/import failed:\", error);"
    print "      res.status(500).json({ error: \"Failed to import products\" });"
    print "    }"
    print "  });"
    next;
}

/^\s*\/\/ --- SUPPLIERS ---/ {
    skip = 0;
}

!skip { print $0; }
' server.ts > server_tmp.ts && mv server_tmp.ts server.ts
chmod +x update_server_products.sh
./update_server_products.sh
